### ISSUE TITLE
unirest to kong: api not found, so OK with curl

### ISSUE THREAD

**Issue by thorstenz** [Mashape/unirest-java#98]
setup is:
--> http SSL --> kong --> service

curl  -X GET --url https://api.domain.io/ping  --header 'apikey: 123'
works.

curl  -X GET --url https://api.domain.io:443/ping  --header 'apikey: 123'
works.

unirest Java:
... Unirest.get("https://api.domain.io:443" + "/ping") ...
not working:
{"path":"/ping","public_dns":["api.domain.io:443"],"message":"API not found with these values"}

**Comment by thibaultCha** [comment]
To query Kong you need a `Host` header. Apparently Unirest sets the `Host` header to `api.domain.io:443`, but I believe your API's `public_dns` is `api.domain.io`.

3 solutions:
- Add a `Host` header to your request, with  `api.domain.io`. So your request will have 2 Host headers but Kong will find the API thanks to the new one.
- Add a `X-Host-Override` header with `api.domain.io`, which acts as an alias to `Host` for Kong
- Set a `path` on your API and instead of relying on headers, Kong will rely on the path requested to find it.

**Comment by thorstenz** [comment]
It is more likely a bug/feature on the kong side: 
host header can have host:port format from reading
this spec in section 14.23: http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html 

unirest is sending a correct host:port combination in the "443" example above and a working theory is:
kong's matching algo does not handle the ":"port part like one would expect.

Do you think is is worth mentioning this on the kong issue list? 
If not changed on the kong side - it would deserve a part in the docs over there ....

Thanks for the work around solutions.

**Comment by thibaultCha** [comment]
It's not much of a bug but simply that Kong expects one of the `Host` or `X-Host-Override` values to match the set `public_dns`. We could make Kong strip the port part of a given header, if any.

**Comment by thibaultCha** [comment]
If you want to list this issue to Kong it's fine with me, I'll implement it :)

**Comment by sinzone** [comment]
should be closed now?

**Comment by thorstenz** [comment]
thank you for taking care. solved.
